backend:
  name: git-gateway
  branch: main
media_folder: 'assets/uploads'
collections:
  - name: 'partners'
    label: 'Partenaire'
    folder: '_partners/'
    create: true
    extension: html
    editor:
      preview: false
    fields:
      - label: Titre
        name: title
      - label: Image
        name: cover
        widget: image
        media_folder: /assets/images/partners
        allow_multiple: false
      - labe: Chapo
        name: description
        widget: markdown
        minimal: true
        buttons: ['bold', 'link', 'bulleted-list']
        editor_components: []
        modes:
          - rich_text
      - labe: Texte
        name: text
        widget: markdown
        minimal: true
        required: false
        buttons: ['bold', 'link', 'bulleted-list']
        editor_components: []
        modes:
          - rich_text
      - label: Partenaire
        name: level
        widget: select
        default: silver
        options: ['silver', 'gold']
      - label: Validé
        name: validated
        widget: boolean
        required: false
      - label: Site
        name: site
        widget: string
        required: false
      - label: Ressources
        name: resources
        widget: list
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
            media_folder: /assets/images/resources
            allow_multiple: false
          - label: Description
            name: description
            widget: markdown
            minimal: true
            buttons: ['bold', 'link']
            editor_components: []
            modes:
              - rich_text
          - label: URL
            name: url
            widget: string
            required: false
