backend:
  name: git-gateway
  branch: main
media_folder: 'assets/uploads'
locale: fr
slug:
  encoding: ascii
  clean_accents: true
collections:
  - name: pages
    label: Pages
    folder: _pages
    extension: html
    editor:
      preview: false
    fields:
      - label: Titre
        name: title
      - label: Chapo
        name: chapo
        widget: markdown
        minimal: true
        buttons: [bold, link, bulleted-list]
        editor_components: []
        modes: ['rich_text']
      - label: Texte
        name: text
        widget: markdown
        minimal: true
        required: false
        buttons: [bold, link, bulleted-list]
        editor_components: []
        modes: [rich_text]
  - name: partners
    label: Partenaires
    label_singular: Partenaire
    folder: '_partners/'
    create: true
    extension: html
    editor:
      preview: false
    fields:
      - label: Titre
        name: title
      - label: Image
        name: cover
        widget: image
        media_folder: /assets/images/partners
        allow_multiple: false
      - labe: Chapo
        name: description
        widget: markdown
        minimal: true
        buttons: [bold, link, bulleted-list]
        editor_components: []
        modes:
          - rich_text
      - labe: Texte
        name: text
        widget: markdown
        minimal: true
        required: false
        buttons: [bold, link, bulleted-list]
        editor_components: []
        modes:
          - rich_text
      - label: Partenaire
        name: level
        widget: select
        default: silver
        options: ['silver', 'gold']
      - label: Validé
        name: validated
        widget: boolean
        required: false
      - label: Site
        name: site
        widget: string
        required: false
      - label: Ressources
        name: resources
        widget: list
        fields:
          - label: Titre
            name: title
            widget: string
          - label: Image
            name: image
            widget: image
            media_folder: /assets/images/resources
            allow_multiple: false
          - label: Description
            name: description
            widget: markdown
            minimal: true
            buttons: ['bold', 'link']
            editor_components: []
            modes:
              - rich_text
          - label: URL
            name: url
            widget: string
            required: false
  - name: persons
    label: Personnes
    label_singular: Personne
    folder: _persons
    create: true
    editor:
      preview: false
    fields:
      - { label: Nom complet, name: title }
      - { label: Prénom, name: first_name }
      - { label: Nom, name: last_name }
      - label: Image
        name: image
        widget: image
        media_folder: /assets/images/people
        allow_multiple: false
      - { label: Description, name: description, required: false, widget: text }
      - { label: Organisation, name: company, required: false }
      - { label: LinkedIn, name: linkedin, required: false }
      - { label: 'Afficher dans la page équipe ?', name: team, widget: boolean, required: false }
  - name: events
    label: Événements
    label_singular: Événement
    folder: _events
    create: true
    extension: html
    editor:
      preview: false
    fields:
      - { label: Titre, name: title }
      - { label: Type, name: kind, hint: 'Avec une capitale initiale (ex: Talk)' }
      - { label: Jour, name: day, hint: 'Au format jj/mm/yyyy'  }
      - { label: Début, name: start, hint: 'Au format 14:00' }
      - { label: Fin, name: end, hint: 'Au format 15:00' }
      - { label: Premier jour, name: first_day, required: false, hint: 'Uniquement pour les événements sur plusieurs jours' }
      - label: Personnes
        name: persons
        widget: relation
        collection: persons
        multiple: true
        search_fields: [title]
        value_field: "{{slug}}"
        display_fields: [title]
